# Оценка качества вина
## Крюков Дмитрий Алексеевич

### 0. Описание задачи

Имеется датасет содержаший физико-химические показатели некоторых вин. По имеющимся данным предсказать оценку качества вина произведенную специалистами.

### 1.Загрузка данных

In [1]:
import numpy as np              
import matplotlib.pyplot as plt
%matplotlib inline 
import pandas as pd
import seaborn as sns
import sklearn

In [2]:
data_path = "./winequalityN.csv"
data_raw = pd.read_csv(data_path)

### 1. Визуализация данных

In [6]:
data_raw.shape

(6497, 13)

Датасет содержит 6497 записей, 13 признаков

In [4]:
data_raw.head()

,type,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,white,7.0,0.27,0.36,20.7,0.045,45.0,170.0,1.0010,3.00,0.45,8.8,6
1,white,6.3,0.30,0.34,1.6,0.049,14.0,132.0,0.9940,3.30,0.49,9.5,6
2,white,8.1,0.28,0.40,6.9,0.050,30.0,97.0,0.9951,3.26,0.44,10.1,6
3,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6
4,white,7.2,0.23,0.32,8.5,0.058,47.0,186.0,0.9956,3.19,0.40,9.9,6

Значение признаков таблицы

1. fixed acidity  
Фиксированная кислотность вина, обусловлена наличем неиспаряемых кислот  

2. volatile acidity  
Количество испаряемых кислот в вине  

3. citric acid  
Количество лимонной кислоты в вине  

4. residual sugar  
Количество сахара, оставшегося после прекращения брожения  

5. chlorides  
Количество соли в вине  

6. free sulfur dioxide  
Свободная форма SO2, находится в равновесии между молекулярной формой и формой бисульфатного иона  

7. total sulfur dioxide  
Количество свободных и связанных форм S02  

8. density  
Плотность  

9. pH  
Описывает, насколько кислое или щелочное вино по шкале от 0 до 14  

10. sulphates  
Содержание сульфатов  

11. alcohol  
Процентное содержание алкоголя в вине  

12. quality  
Выходная оценка качества вина

In [9]:
data_raw.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,6487.000000,6489.000000,6494.000000,6495.000000,6495.000000,6497.000000,6497.000000,6497.000000,6488.000000,6493.000000,6497.000000,6497.000000
mean,7.216579,0.339691,0.318722,5.444326,0.056042,30.525319,115.744574,0.994697,3.218395,0.531215,10.491801,5.818378
std,1.296750,0.164649,0.145265,4.758125,0.035036,17.749400,56.521855,0.002999,0.160748,0.148814,1.192712,0.873255
min,3.800000,0.080000,0.000000,0.600000,0.009000,1.000000,6.000000,0.987110,2.720000,0.220000,8.000000,3.000000
25%,6.400000,0.230000,0.250000,1.800000,0.038000,17.000000,77.000000,0.992340,3.110000,0.430000,9.500000,5.000000
50%,7.000000,0.290000,0.310000,3.000000,0.047000,29.000000,118.000000,0.994890,3.210000,0.510000,10.300000,6.000000
75%,7.700000,0.400000,0.390000,8.100000,0.065000,41.000000,156.000000,0.996990,3.320000,0.600000,11.300000,6.000000
max,15.900000,1.580000,1.660000,65.800000,0.611000,289.000000,440.000000,1.038980,4.010000,2.000000,14.900000,9.000000

* Количество значений для разных столбцоы различно, в таблице имеются отсутсвующие значения
* Среднее качество вина 5.8, стандартное отклонение 0.87. Большая часть значений находится в иапазоне от 5 до 7
* Стандартное отклонение параметра плотность равно 0.002999, значения отличаются несущественно